### ISSUE TITLE
Regression in 1.006

### ISSUE THREAD

**Issue by Ovid** [karenetheridge/Test-JSON-Schema-Acceptance#21]
Our team has a local fork of [JSON::Validator](https://github.com/SysPete/json-validator) because we need to get it running on 5.8. However, when I run this:

```
TEST_ACCEPTANCE=1 prove -l t/draft2019-09-acceptance.t
```

One of the TODO tests fails on 1.006. When we downgrade to 1.005, it passes (verified by two devs, on on MacOS and another on Debian). Full test output:

```
t/draft2019-09-acceptance.t .. 143/?     # Failed test 'test failed'
    # at t/Helper.pm line 54.
    # expected false; got true

# Failed test 'defs.json: "validate definition against metaschema" - "invalid definition schema"'
# at t/Helper.pm line 54.
t/draft2019-09-acceptance.t .. 954/? # Looks like you failed 1 test of 987.
t/draft2019-09-acceptance.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/987 subtests
        (136 TODO tests unexpectedly succeeded)

Test Summary Report
-------------------
t/draft2019-09-acceptance.t (Wstat: 256 Tests: 987 Failed: 1)
  Failed test:  192
  TODO passed:   63-64, 145-148, 660-691, 712, 723, 726-727
                830-923
  Non-zero exit status: 1
Files=1, Tests=987, 20 wallclock secs ( 0.21 usr  0.01 sys + 18.91 cusr  0.68 csys = 19.81 CPU)
Result: FAIL

shell returned 1
```

**Comment by karenetheridge** [comment]
You should be reporting this to JSON::Validator, not here. This distribution bundles the official test suite from https://github.com/json-schema/JSON-Schema-Test-Suite and the code itself has not changed between 1.005 and 1.006.

**Comment by karenetheridge** [comment]
The test is here - as it is a very straightforward test I see no reason why a validator should be failing it.

https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft2019-09/defs.json
